### ISSUE TITLE
DHTML is being created (way) too early!

### ISSUE THREAD

**Issue by DBotThePony** [photonle/Photon#128] opened 2020-02-07 08:12 UTC
https://github.com/photonle/Photon/blob/development/lua/autorun/photon/cl_photon_hud.lua#L587 this line should be put onto https://wiki.facepunch.com/gmod/GM:OnGamemodeLoaded (or more late hook, such as https://wiki.facepunch.com/gmod/GM:InitPostEntity) hook, instead of attempting to create panel right after hud Lua file is initialized (on autorun, before vgui/gamemode but after include/init.lua)

```
Warning: vgui.Create failed to create the VGUI component (DHTML)

[Photon: Lighting Engine] lua/autorun/photon/cl_photon_hud.lua:304: Panel "DHTML" does not exist.
  1. error - [C]:-1
   2. Create - addons/dlib/lua/dlib/luabridge/luabridge.lua:189
    3. unknown - addons/dlib/lua/dlib/luabridge/luabridge.lua:243
     4. ProtectedCall - [C]:-1
      5. Create - addons/dlib/lua/dlib/luabridge/luabridge.lua:242
       6. Init - lua/autorun/photon/cl_photon_hud.lua:304
        7. unknown - lua/autorun/photon/cl_photon_hud.lua:585
         8. include - [C]:-1
          9. unknown - lua/autorun/photon/sh_photon_init.lua:104
           10. include - [C]:-1
            11. unknown - lua/autorun/emv_init.lua:12


[Photon: Lighting Engine] addons/dlib/lua/dlib/luabridge/luabridge.lua:247: Cannot create panel "DHTML"! Look for errors above
  1. error - [C]:-1
   2. Create - addons/dlib/lua/dlib/luabridge/luabridge.lua:247
    3. Init - lua/autorun/photon/cl_photon_hud.lua:304
     4. unknown - lua/autorun/photon/cl_photon_hud.lua:585
      5. include - [C]:-1
       6. unknown - lua/autorun/photon/sh_photon_init.lua:104
        7. include - [C]:-1
         8. unknown - lua/autorun/emv_init.lua:12
```

**Comment by JoshPiper** [comment] 2020-02-07 20:43
Thanks for submitting the issue.

This is already handled internally by checking the [return of vgui.Create](https://github.com/photonle/Photon/blob/development/lua/autorun/photon/cl_photon_hud.lua#L304-L305), with the breaking error is caused by a [wrapper around vgui.Create](https://github.com/DBotThePony/DLib/blob/develop/lua_src/dlib/luabridge/luabridge.lua#L187-L193) in an external addon.

Moving this hook is an enhancement, not a bug, and isn't a high priority right now.

**Comment by DBotThePony** [comment] 2020-02-08 06:59
It can start to throw errors though in future versions of gmod. And you already put a hack by checking vgui.Create return value, when in proper case it should already return a valid Panel (hence it is a bug - relying on undocumented feature is a no no).

**Closed as completed** 2020-02-11 16:48 UTC
Labels: enhancement
